nova_poshta/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('tracking.urls')),
]

tracking/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
#    url(r'^delete_parcels/$', views.delete_parcels, name='delete_parcels'),
    url(r'^$', views.parcel_list, name='parcel_list'),
    url(r'^parcel/(?P<pk>\d+)/$', views.parcel_edit, name='parcel_edit'),
    url(r'^parcel/new/$', views.parcel_new, name='parcel_new'),
    url(r'^delete_parcels/$', views.delete_parcels, name='delete_parcels'),
]

tracking/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from datetime import date

# Create your models here.

class Parcel(models.Model):
    track_number = models.CharField(max_length=50)
    city = models.CharField(max_length=200)
    client_name = models.CharField(max_length=200)
    phone_number = models.CharField(max_length=50)
    payment_summ = models.FloatField(max_length=200)
    departure_date = models.DateField(default=date.today)
    days_after_departure = models.PositiveSmallIntegerField()
    status = models.CharField(max_length=200)

#    def add_parcel(self):
#        self.save()

tracking/forms.py
from django import forms

from .models import Parcel

class ParcelForm(forms.ModelForm):

    class Meta:
        model = Parcel
        fields = ('track_number', 'city', 'client_name', 'phone_number', 'payment_summ', 'departure_date' )

tracking/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, get_object_or_404
from datetime import datetime, date
from .models import Parcel
from .forms import ParcelForm
import requests
import json
from django.views.decorators.csrf import csrf_exempt
from django.contrib import messages

# Create your views here.

def parcel_list(request):
    parcels = Parcel.objects.all()
    for iks in parcels:
        api_domain = 'https://api.novaposhta.ua'
        api_path = '/v2.0/json/'
        api_data = {
                'modelName': "TrackingDocument",
                'calledMethod': "getStatusDocuments",
                'methodProperties': {
                    "Documents": [
                        {
                        "DocumentNumber": iks.track_number
                        }
                    ]
                    }
                }
        r = requests.post(api_domain + api_path, json=api_data).json()
        parcel_status = r['data'][0]['Status']
        iks.status = parcel_status
        iks.save(update_fields=["status"])
        today = date.today()
        departure_date = iks.departure_date
        difference = abs(today - departure_date)
        difference = difference.days
        iks.days_after_departure = difference
        iks.save(update_fields=["days_after_departure"])
    return render(request, 'tracking/parcel_list.html', {'parcels': parcels} )

def parcel_new(request):
    if request.method == "POST":
        form = ParcelForm(request.POST)
        if form.is_valid():
            parcel = form.save(commit=False)
            parcel.days_after_departure = 0
            api_domain = 'https://api.novaposhta.ua'
            api_path = '/v2.0/json/'
            api_data = {
                    'modelName': "TrackingDocument",
                    'calledMethod': "getStatusDocuments",
                    'methodProperties': {
                        "Documents": [
                            {
                            "DocumentNumber": parcel.track_number
                            }
                        ]
                        }
                    }
            r = requests.post(api_domain + api_path, json=api_data).json()
            parcel_status = r['data'][0]['Status']
            parcel.status = parcel_status
            if parcel_status == "Номер не знайдено":
                messages.error(request,'Номер посылки не верный')
                return redirect('parcel_new')
            else:
                parcel.save()
                return redirect('parcel_list')
#            return render(request, 'tracking/parcel_list.html', {'parcel.status': parcel.status}, {'parcel.days_after_departure': parcel.days_after_departure})
    else:
        form = ParcelForm()
    return render(request, 'tracking/parcel_new.html', {'form': form})

def parcel_edit(request, pk):
    parcel = get_object_or_404(Parcel, track_number=pk)
    if request.method == "POST":
        form = ParcelForm(request.POST, instance=parcel)
        if form.is_valid():
            parcel = form.save(commit=False)
            parcel.days_after_departure = 0
            api_domain = 'https://api.novaposhta.ua'
            api_path = '/v2.0/json/'
            api_data = {
                    'modelName': "TrackingDocument",
                    'calledMethod': "getStatusDocuments",
                    'methodProperties': {
                        "Documents": [
                            {
                            "DocumentNumber": parcel.track_number
                            }
                        ]
                        }
                    }
            r = requests.post(api_domain + api_path, json=api_data).json()
            parcel_status = r['data'][0]['Status']
            parcel.status = parcel_status
            if parcel_status == "Номер не знайдено":
                messages.error(request,'Номер посылки не верный')
                return redirect('parcel_edit', pk=pk)
            else:
                parcel.save()
                return redirect('parcel_list')
    else:
        form = ParcelForm(instance=parcel)
    return render(request, 'tracking/parcel_edit.html', {'form': form})

@csrf_exempt
def delete_parcels(request, id=None):
    if request.method == 'POST':
        values = request.POST.getlist('checkbox_list')
        for parcel_id in values:
            Parcel.objects.get(id=parcel_id).delete()
        return redirect('parcel_list')

tracking/templates/tracking/base.html
{% load static %}
<html>
<head>
    <title>Parcel Tracker</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
  <body>
      <div class="page-header">
          <h1><a href="/">Где посылка?</a></h1>
      </div>

              {% block content %}
              {% endblock %}

  </body>
</html>

tracking/templates/tracking/parcel_edit.html
{% extends 'tracking/base.html' %}


{% block content %}

<form method="POST" class="post-form">
    <h1>Редактировать посылку</h1>
  {% csrf_token %}
{% for message in messages %}

               <div class="alert alert-success">
                   <a class="close" href="#" data-dismiss="alert">×</a>

                   {{ message }}

               </div>
       {% endfor %}
{{ form.non_field_errors }}
<div class="fieldWrapper">
{{ form.track_number.errors }}
<label for="id_track_number">Номер посылки*:</label>
{{ form.track_number }}
</div>

<div class="fieldWrapper">
{{ form.city.errors }}
<label for="id_city">Город*:</label>
{{ form.city }}
</div>

<div class="fieldWrapper">
{{ form.client_name.errors }}
<label for="id_client_name">ФИО*:</label>
{{ form.client_name }}
</div>

<div class="fieldWrapper">
{{ form.phone_number.errors }}
<label for="id_phone_number">Телефон*:</label>
{{ form.phone_number }}
</div>

<div class="fieldWrapper">
{{ form.payment_summ.errors }}
<label for="id_payment_summ">Сумма наложенного платежа*:</label>
{{ form.payment_summ }}
</div>

<div class="fieldWrapper">
{{ form.departure_date.errors }}
<label for="id_departure_date">Дата отправки*:</label>
{{ form.departure_date }}
</div>
<div id="form_fields">*Поля обязательные для заполнения</div>
<div id="save_button">
    <button type="submit" class="save btn btn-default">Сохранить</button>
  </div>
</form>
{% endblock %}

tracking/templates/tracking/parcel_list.html
{% extends 'tracking/base.html' %}

{% block content %}
  <script language="JavaScript">
  function toggle(source) {
  checkboxes = document.getElementsByName('checkbox_list');
  for(var i=0, n=checkboxes.length;i<n;i++) {
    checkboxes[i].checked = source.checked;
  }
}
  </script>

  <!--  <button type="submit" name="delete" class="btn btn-default pull-right">Удалить</button> -->
    <form action="{% url 'delete_parcels' %}" method="POST">
      <div id="add_button"> <a class="btn btn-default" href="{% url 'parcel_new' %}" role="button">Добавить посылку</a>
      </div>
      <br>
      {% csrf_token %}
    <div>
    <table id="parcels">
      <tr>
        <th class="text_center"><input type="checkbox" name="select_all" onClick="toggle(this)"/></th>
        <th>№</th>
        <th>Номер посылки</th>
        <th>Город получателя</th>
        <th>ФИО</th>
        <th>Телефон</th>
        <th>Сумма наложенного платежа</th>
        <th>Дата отправки</th>
        <th>Статус</th>
        <th>Дней после отправки</th>
        <th>Изменить</th>
      </tr>
      {% for parcel in parcels %}
      <tr>
       <td class="text_center"><input type="checkbox" name="checkbox_list" value="{{ parcel.id }}"></td>
       <td class="counter"></td>
       <td><a href="https://novaposhta.ua/tracking/?cargo_number={{ parcel.track_number }}" target="_blank">{{ parcel.track_number }}</a></td>
       <td>{{ parcel.city }}</td>
       <td>{{ parcel.client_name }}</td>
       <td>{{ parcel.phone_number }}</td>
       <td>{{ parcel.payment_summ }}</td>
       <td>{{ parcel.departure_date }}</td>
       <td>{{ parcel.status }}</td>
  <!--     <td>{{ parcel.days_after_departure }} </td> -->
       {% if parcel.days_after_departure > 5 %} <td class="red"> {{ parcel.days_after_departure }} </td>
       {%else %}  <td class="text_center">{{ parcel.days_after_departure }} </td>
       {% endif %}
            <td class="text_center"><a class="btn btn-default" href="{% url 'parcel_edit' pk=parcel.track_number %}"><span class="glyphicon glyphicon-pencil"></span></a></td>
      </tr>
      {% endfor %}
    </table>
  </div><br>
  <div id="delete_button"> <input type="submit" name="delete" class="btn btn-default pull-left" value="Удалить"></div>
  </form>
{% endblock %}

tracking/templates/tracking/parcel_new.html
{% extends 'tracking/base.html' %}

{% block content %}

    <form method="POST" class="post-form">
        <h1>Добавить посылку</h1>
      {% csrf_token %}
  {% for message in messages %}

                   <div class="alert alert-success">
                       <a class="close" href="#" data-dismiss="alert">×</a>

                       {{ message }}

                   </div>
           {% endfor %}
    {{ form.non_field_errors }}
<div class="fieldWrapper">
    {{ form.track_number.errors }}
    <label for="id_track_number">Номер посылки*:</label>
    {{ form.track_number }}
</div>

<div class="fieldWrapper">
    {{ form.city.errors }}
    <label for="id_city">Город*:</label>
    {{ form.city }}
</div>

<div class="fieldWrapper">
    {{ form.client_name.errors }}
    <label for="id_client_name">ФИО*:</label>
    {{ form.client_name }}
</div>

<div class="fieldWrapper">
    {{ form.phone_number.errors }}
    <label for="id_phone_number">Телефон*:</label>
    {{ form.phone_number }}
</div>

<div class="fieldWrapper">
    {{ form.payment_summ.errors }}
    <label for="id_payment_summ">Сумма наложенного платежа*:</label>
    {{ form.payment_summ }}
</div>

<div class="fieldWrapper">
    {{ form.departure_date.errors }}
    <label for="id_departure_date">Дата отправки*:</label>
    {{ form.departure_date }}
</div>
<div id="form_fields">*Поля обязательные для заполнения</div>
<div id="save_button">
        <button type="submit" class="save btn btn-default">Добавить</button>
      </div>
    </form>
{% endblock %}